### ISSUE TITLE
Selectize doesn't work when in a container that initially had display none

### ISSUE THREAD

**Issue by airblade** [selectize/selectize.js#1036]
I have a tabs widget with two tabs.  Each tab has a `<select>` which I call `selectize()` on.

Originally both tabs would be rendered on page load, then javascript would kick in on `document.ready` and set one of the tab's `display` to `none`.

However that lead to a "flash of unwanted tabs".  So I changed the CSS so the tab divs have `display: none`, and then the javascript sets the appropriate tab's `display` to `block`.

Unfortunately that prevents Selectize from doing its thing.  The `<select>`s just sit there without being selectized.

How can I fix this?

Many thanks in advance.

**Comment by airblade** [comment]
Fixed: the problem was my code not Selectize.  Sorry for the noise.

**Comment by vanboom** [comment]
I am having the same issue with a CSS based tab layout - how did you resolve this?

**Comment by airblade** [comment]
My html looked like this:

```html
<div id="tabs">
  <ul>
    <li class="active">First tab label</li>
    <li>Second tab label</li>
  </ul>
</div>
<div id="innerinfo">
  <div class="active">
    <!-- first tab content including selectize -->
  </div>
  <div>
    <!-- second tab content including selectize -->
  </div>
</div>
```

The problem was that my CSS looked like this:

```css
#innerinfo div {
  display: none;
}
#innerinfo div.active {
  display: block;
}
```

The solution was to change the CSS to this:

```css
#innerinfo > div {
  display: none;
}
#innerinfo > div.active {
  display: block;
}
```

Looking back I don't know why I settled on that html structure; I do it differently these days!
