### ISSUE TITLE
Drop Down Icon Missing on Select Element with Multiple Attribute

### ISSUE THREAD

**Issue by jblacker** [selectize/selectize.js#1232]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [x] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

When Selectize is intialized on a `<select>` element with the `multiple` flag the icon on the right hand side of the input component is missing.   This is does NOT occur on `<select>` elements without the multiple flag or on text fields.  I have not tested any other themes, but this occurs with the `selectize.bootstrap3.css` stylesheet.

Steps to reproduce:

1. Create a select element with the multiple flag and put a few options already in it.
2. Initialize selectize on the element
3. Look :eyes: 

Here's a minimal Codeply that shows the issue:  http://www.codeply.com/go/sJ9HoFi1Xe

**Comment by ildarnm** [comment]
+1

**Comment by northwood-dev** [comment]
Same problem for me with default theme.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.

**Comment by dometto** [comment]
Anyone find a workaround for this?

**Comment by dometto** [comment]
Actually, just copying the relevant style for the single select (`.selectize-control.single`) from `selectize.bootstrap4.css` and applying it to `.selectize-control` does the trick:

```css
.selectize-control .selectize-input:after{content:" ";display:block;position:absolute;top:50%;right:calc(0.75rem + 5px);margin-top:-3px;width:0;height:0;border-style:solid;border-width:5px 5px 0 5px;border-color:#343a40 rgba(0,0,0,0) rgba(0,0,0,0) rgba(0,0,0,0)}

.selectize-control .selectize-input.dropdown-active:after{margin-top:-4px;border-width:0 5px 5px 5px;border-color:rgba(0,0,0,0) rgba(0,0,0,0) #343a40 rgba(0,0,0,0)}
```
