### ISSUE TITLE
[Feature Request] Option that disables inline `display` and `visibility` CSS on dropdown

### ISSUE THREAD

**Issue by yandodov** [selectize/selectize.js#1344]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [ ] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [ ] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

**This is a feature request!**

I wanted to add animations to my dropdown by utilizing the `.dropdown-active` class and the `visibility` property. To have that work, the dropdown had to always be `display: block` and have `visibility: hidden` in the absence of `.dropdown-active` and `visible` when it's present.

Basically, I had to remove some of the inline CSS added by Selectize. The `width`, `top` and `left` is perfect and always needed. But `display` and `visibility` should be chosen by the user.

I had to do the following to make it work:

```js
function unstyleDropdown($dropdown) {
    $dropdown = $dropdown || this.$dropdown;

    if ($dropdown) {
        $dropdown.css("display", "");
        $dropdown.css("visibility", "");
    }
}

$(".foo").selectize({
    onInitialize: function () {
        unstyleDropdown();
    },

    onDropdownOpen: unstyleDropdown,
    onDropdownClose: unstyleDropdown
});
```
```css
.selectize-input.dropdown-active + .selectize-dropdown {
    visibility: visible;
    opacity: 1;
}

.selectize-dropdown {
    display: block;
    visibility: hidden;
    opacity: 0;

    transition: all 0.3s ease;
}
```
Would be nice if I could reduce the JavaScript part to just:
```js
$(".foo").selectize({
    noDisplayCSS: true
});
```

---

Hope to see this implemented!
**Thank You!**
