### ISSUE TITLE
Custom loading indicator beyond loadingClass

### ISSUE THREAD

**Issue by aureole82** [selectize/selectize.js#1469]
I walked through all examples of selectize.js (Version 0.12.6) and found the spinner of [movies.html](https://github.com/selectize/selectize.js/blob/master/examples/movies.html).
This example uses some cumbersome css to display an image (`spinner.gif`) if the `loading` class is present:
```css
.selectize-control.movies::before {
    -moz-transition: opacity 0.2s;
    -webkit-transition: opacity 0.2s;
    transition: opacity 0.2s;
    content: ' ';
    z-index: 2;
    position: absolute;
    display: block;
    top: 12px;
    right: 34px;
    width: 16px;
    height: 16px;
    background: url(images/spinner.gif);
    background-size: 16px 16px;
    opacity: 0;
}
.selectize-control.movies.loading::before {
    opacity: 0.4;
}
```

**We cannot provide an extra image.** We rather like to use a web font (like FontAwesome's [`<i class="fas fa-spinner fa-spin"></i>`](https://fontawesome.com/how-to-use/on-the-web/styling/animating-icons)).
I know how to hide/show elements below `div.selectize-control.loading`. **But the question is: What's the best way to place my custom elements inside `div.selectize-control`?**

Thanks alot in advance!
