### ISSUE TITLE
Support for Bootstrap 5

### ISSUE THREAD

**Issue by alranel** [selectize/selectize.js#1584]
In case anyone needs this, I was able to adapt the Bootstrap 4 theme to work with Bootstrap 5 by just adding the following overrides:

```css
.selectize-control {
    padding: 0;
}
.selectize-input {
    border: none;
}
```
