### ISSUE TITLE
style when item width doesn't fit into select container

### ISSUE THREAD

**Issue by kulbakin** [selectize/selectize.js#377]
There is a bug with style when item doesn't fit into container width
http://screencast.com/t/7Shnv5uykX
I suppose the area under arrow must be opaque.

Also i would be great to have selectize to treat long text with spaces as default select does, i.e. truncating it into single line instead of making select box multiline.

**Comment by prograhammer** [comment]
@benmj  Great plugin! Thank you!

**Comment by ghost** [comment]
It could be done with css

``` css
/* fixed width */
.selectize-input > * {
  vertical-align: middle;
}
.selectize-input .item {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  max-width: 150px;
}

/* respnonsive */
.selectize-input {
  display: table !important;
  table-layout: fixed;
  width: 100%;
}
.selectize-input > * {
  vertical-align: middle;
}
.selectize-input .item {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  max-width: 80%;
}
```
