### ISSUE TITLE
Why do style for bootstrap-3?

### ISSUE THREAD

**Issue by comerc** [selectize/selectize.js#667]
fix:

``` css
.selectize-dropdown, .selectize-input, .selectize-input input { font-family:inherit; font-size:inherit; }
```
