### ISSUE TITLE
BUGFIX: bootstrap3 border focus 

### ISSUE THREAD

**Issue by comerc** [selectize/selectize.js#671]
``` css
.form-control > .selectize-input {
    -webkit-transition: inherit; 
    -moz-transition: inherit; 
    -o-transition: inherit; 
    transition: inherit;
}
```
