### ISSUE TITLE
missing style for optgroup

### ISSUE THREAD

**Issue by ghost** [selectize/selectize.js#843]
- [without fix](http://prntscr.com/745t98)
- [with fix](http://prntscr.com/745tkf)

``` css
.selectize-dropdown .optgroup-header {
    font-weight: bold;
    font-size: 14px;
}
.selectize-dropdown .optgroup .option {
    padding-left: 20px;
}
```
