### ISSUE TITLE
Placeholder text is clipped on Firefox

### ISSUE THREAD

**Issue by philostler** [selectize/selectize.js#851]
On Firefox 39 OS X (not tested on earlier versions of FF) the placeholder text is initially rendered too small and clips trailing characters. This only happens on FF, Chrome and Safari work as expected.

After selecting the control and deselecting, the placeholder expands and is no longer clipped.

<img width="584" alt="before interaction" src="https://cloud.githubusercontent.com/assets/244198/8729984/274b1a48-2be6-11e5-8040-c408427b678c.png">
<img width="581" alt="after interaction" src="https://cloud.githubusercontent.com/assets/244198/8729988/2d417e88-2be6-11e5-9644-c40ba9a659f7.png">

**Comment by PhiLhoSoft** [comment]
My experience is the opposite, I see the problem in Chrome, not in Firefox. Perhaps it depends on the chosen theme (Bootstrap 3 in my case) or the used font.
As a ( bad) workaround, we add spaces at the end of the placeholder.
I think the main issue is in the computation of the width of the text, done in the measureString function. Perhaps some CSS properties are missing (I wonder already at the missing fontStyle, although that's not the issue here).

**Comment by philostler** [comment]
@PhiLhoSoft I'm using the Bootstrap 3 theme as a base as well so we have cross over there. Nice thought on the workaround, I'll go with that until there's a fix. cheers!

**Comment by karan-kang** [comment]
This bug is reproducible on IE 11 also. This fixed it for me:

```
.selectize-input > input[placeholder] {
  width: 100% !important;
}
```

**Comment by addzies** [comment]
In the measureString function I changed the width value from 'auto' to '100%'  and that worked.

**Comment by bhantol** [comment]
+1 
ditto happening in ie11.

@addzies Adding 100% solves the problem only if your selectize is well placed in proper columns (bootstrap grid etc.). With 100% width when the `<test>` is added to the `<body>` may result into the full viewport width.

The problems seems to be +4 in the call after 
        `measureString(val) + 4` 

4 pixels are not nearly enough after the initial space that browsers add to the placeholders in the input.

**Comment by joallard** [comment]
Looks like we'd need something more reliable for autogrow than "oh, let's add N pixels here"

**Comment by landondurnan** [comment]
Was running into this issue and it was related to the styles on the input inside selectize:

```
.selectize-input {
  input[type="text"] {
    padding: 0 20px 0 0;
  }
}
```

The above resulted in clipping 20px.

The padding isn't needed and when it's added on render throws off the width of the input depending on your box model.

**Comment by yoramdelangen** [comment]
Same issue but resolved it by setting the `box-sizing` instead of `border-box` i've put it on `initial` and now its showing it proper while using `padding`.

This fixed it for me: 

``` css
.selectize-input {
    input[placeholder] {
        box-sizing: initial;
    }
}
```

Because the width calculator is not keeping track of already existing paddings and/or detecting the `border-sizing` settings. If I would set the width to `width: 100% !important` it would give me not the effect of an labeled input field.

**Comment by kniziol** [comment]
Some problem here. MacOS + Google Chrome 55.0.2883. Using Bootstrap 3 and these styles for placeholders in inputs:

```css
::-moz-placeholder {
    color: #aaa;
    opacity: 1; // Override Firefox's unusual default opacity; see https://github.com/twbs/bootstrap/pull/11526
    font-family: 'WorkSans Light', sans-serif;
    text-align: center;
    text-transform: uppercase;
}
:-ms-input-placeholder {
    color: #aaa;
    font-family: 'WorkSans Light', sans-serif;
    text-align: center;
    text-transform: uppercase;
}
::-webkit-input-placeholder {
    color: #aaa;
    font-family: 'WorkSans Light', sans-serif;
    text-align: center;
    text-transform: uppercase;
}
```

## Solution
```css
.selectize-input:not(.has-items) input {
    text-align: center;
    width: 100% !important;
}
```

## Before
![before](https://cloud.githubusercontent.com/assets/947620/21105829/f84148b2-c08b-11e6-9a5c-5113b62051bc.jpg)

## After
![after](https://cloud.githubusercontent.com/assets/947620/21105839/ff62c6d4-c08b-11e6-980d-de1671f6dee5.jpg)
