### ISSUE TITLE
Set focus border

### ISSUE THREAD

**Issue by matthewtbaker** [selectize/selectize.js#983]
Please can you add an additional variable `$selectize-border-active` and modify the `.selectize-input` css to allow for a different border (primarily color) on `:focus`.  This will remove the need to add it to the core code which will be lost on upgrades.  Maybe good to have `$selectize-border-hover` too...

``` css
.selectize-input {
&.focus {
        @include selectize-box-shadow ($selectize-shadow-input-focus);
        border: $selectize-border-active; /* add this */
    }
}
```

Many thanks.
